export const SIGUP_REQUEST="SIGNUP_REQUEST"
export const SIGUP_SUCCESSFUL="SIGNUP_SUCCESSFUL"
export const SIGUP_FAILURE="SIGNUP_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESSFUL="LOGIN_SUCCESSFUL"
export const LOGIN_FAILURE="LOGIN_FAILURE"


